### ISSUE TITLE
Couple of bugs and changes request

### ISSUE THREAD

**Issue by dynsky** [manifoldfinance/staking#19]
Bugs

-Graphic bug presented in photo

-"Permit FOLD to mint and stake xFOLD" and "Complete Staking" buttons does the same, asks for approving FOLD

-Although user approved before manually interacting with contract, site still asks for approving (this issue might be connected to second one, as i don't know how it behaves normally)

-After clicking withdraw button, "to is not defined" pops up in lower right corner

-Users on telegram are reporting that if you left staking process in half, for example after approving and closing site they need to approve again, thats why mobile users might not be able to stake at all, because signing every transaction in wallet might be counting as leaving page thus resetting whole process (1 user reported this mobile issue)

Changes request

-Move xFOLD approval to withdraw section, doing 3 transactions in order to stake is making people confused, basing on telegram discussion

-After opening site and not logging into metamask straight away, clicking connect wallet and choosing it produces an error "Connect to site / This provider is not supported."

Browser: firefox 95.0.2

![xfoldbug](https://user-images.githubusercontent.com/96447749/146896616-16fe2777-5bcc-4730-bce5-69b4c45b9f11.png)

**Comment by sambacha** [comment]
this should be addressed in https://github.com/manifoldfinance/staking/pull/20

**Comment by dunno11** [comment]
@sambacha site stopped asking to approve fold again but its still asking to approve xfold that is already approved
also now both deposit and withdrawal is asking for xfold approval, not sure if this is desired outcome

**Comment by sambacha** [comment]
> @sambacha site stopped asking to approve fold again but its still asking to approve xfold that is already approved also now both deposit and withdrawal is asking for xfold approval, not sure if this is desired outcome

Can you provide a transaction hash / address ? you can email me: sam@manifoldfinance.com if you dont want to post it here

**Comment by dunno11** [comment]
sure, i just sent you the data

**Comment by dunno11** [comment]
@sambacha ser just to clarify, im not the only one with quoted issues, other users also report it
