### ISSUE TITLE
Bug: some users can inadvertently pick a null address as the msg.sender

### ISSUE THREAD

**Issue by sambacha** [manifoldfinance/staking#21]
Reported to me via telegram (sic)

>  I used the dApps to unstake xFOLD ( withdraw ).
> But it only burned my xFOLD and seems not getting back my FOLD tokens.
> I also did it 4 days ago manualy, on etherscan, just for testing.
> and it also burned my xFOLD and not getting back my FOLD token.
> the Transaction Details are

[https://etherscan.io/tx/0x7c7aacdf141620a051301cfc275bf11a2d0494664cf5842b70824951fc3cd11d](https://etherscan.io/tx/0x7c7aacdf141620a051301cfc275bf11a2d0494664cf5842b70824951fc3cd11d)

**Comment by sambacha** [comment]
as the comment in telegram says, it was there usage of etherscan app to unstake, withdrawing/unstaking was never connected until now, see #30

**Comment by dynsky** [comment]
as i said in that issue spender address was correct in withdraw section which is why people were able to use unstake through dapp successfully, wrong spender address in deposit section wasn't making unstaking not possible
both deposit and withdraw are asking for xfold approvals
