### ISSUE TITLE
7 users lost access to their tokens after unstaking on dapp during 22-24 December

### ISSUE THREAD

**Issue by dynsky** [manifoldfinance/staking#26]
Users lost access to their tokens after unstaking on dapp, XFOLD has been burned and FOLD wasn't sent to them back. instead of sending FOLD to their addresses, FOLD was sent to manifold contract address. tx example https://etherscan.io/tx/0x67dd341bf81670839a83df63ca105bac14d6937c0f50fee4ad7d58efa258f94d

complete list of addresses that lost access due to this bug (burn label)
https://etherscan.io/token/0xd084944d3c05cd115c09d072b9f44ba3e0e45921?a=0xd084944d3c05cd115c09d072b9f44ba3e0e45921

this issue is connected to #21 although users are no longer affected by this bug people who lost due to it still aren't given their tokens back.

**Comment by sambacha** [comment]
we will track this issue in the forums as its not related to the front end UI 

https://forums.manifoldfinance.com/t/proposal-compensate-lost-tokens-by-transfer/161

thank you for posting this
