### ISSUE TITLE
Staking link on homepage 404s

### ISSUE THREAD

**Issue by NCal** [manifoldfinance/staking#37]
**Describe the bug**
Staking Link on homepage 404s

**Minimal Reproduction Repo / Steps to Reproduce**
1. Go to manifoldfinance.com
2. Click the staking link on the right side of the homepage 

**Expected behavior**
Clicking the staking link should direct the user to https://staking.manifoldfinance.com

**Screenshots**
Link is appended to domain instead of just linking to  https://staking.manifoldfinance.com
![Screenshot from 2022-01-02 12-59-52](https://user-images.githubusercontent.com/14134575/147885103-0cee4326-0161-4072-a5c0-1d7115764d99.png)

clicking the link 404s:
![Screenshot from 2022-01-02 13-02-15](https://user-images.githubusercontent.com/14134575/147885140-71715dab-8bbb-4a9e-9791-7601531f7690.png)

**Environment:**
any browser (i'm using brave)

**Comment by sambacha** [comment]
should be fixed

**Comment by dynsky** [comment]
@sambacha it was fixed but now its present again, deleting cache isn't resolving it

**Comment by kedos25** [comment]
Staking button works for me (with Firefox on desktop)

**Comment by sambacha** [comment]
new website launching tomorrow , feedback welcomed from yall 

thanks
