### ISSUE TITLE
feature request: approval button that is always present

### ISSUE THREAD

**Issue by ghost** [manifoldfinance/staking#48]
dapp won't prompt for approval when user has any approved amount
users that have approved value greater than 0 and it isn't matching with their current stake amount aren't be able to stake through dapp

feature request: additional approval button that is always present and gives ability to approve desired amount

**Comment by sambacha** [comment]
I have assigned @NtwaliHeritier to this task - this is a bug and not a feature request! we will get this fixed ASAP thank you for reporting this
